export const EXPERIENCES = [
  {
    title: "Senior Software Engineer I",
    period: "April 2024 - Present",
    company: "JULO Tekonologi Finansial",
    employmentType: "Full-time",
    location: "Remote",
    responsibilities: [
      "Initiate and supervise the code on Merchant Financing Standard Product (new product).",
      "Initiate and supervise the code on Leadgen Financing Standard Product (new product).",
      "Create a template project that can enhance initialize time of building new product.",
      "Create automation in Github Worlflow that could help boost productivity ex: PR Check, Auto Publish, Manual Publish, etc.",
      "Supervising 2 engineers that works in my current squad.",
      "Supervise code quality by doing thorough code review that makes the project stable, maintainable and scalable.",
      "Design OTP Flow that enhance in UX and security when request, verify the otp.",
      "Currently working on enhancing security by refactoring the flow of Authentication using OAuth flow by implementing Set-Cookie, HTTP-only cookies, and SSR.",
    ],
    current: true,
  },
  {
    title: "Web Frontend Engineer",
    period: "January 2023 – April 2024",
    company: "JULO Tekonologi Finansial",
    employmentType: "Full-time",
    location: "Remote",
    responsibilities: [
      "Initiate restructuring using concept of SoC (Separation of Concerns) that result in reduced 60% lines of code in every component and increase readability and maintainability.",
      "Initiate restructuring BE API response that resulting in the API use a proper HTTP status, clean and structured response object.",
      "Migrating old project that still using Javascript to Typescript.",
      "Build UI Library (julo-ui) that implement JULO Design System to be used by all Web FE Engineer across Tribe/Squad for their projects",
      "Initiate building dashboard and merchant page for partner Axiata.",
      "Build Julo Liveness library to be used by all Web Engineer across Tribe/Squad to enhance security in the credit-score checking.",
      "Sharing knowledge across Web FE Engineer regarding best practices and new technology research.",
    ],
    current: false,
  },
  {
    title: "Software Engineer Web Platform",
    period: "August 2022 – December 2022",
    company: "Tokopedia",
    employmentType: "Full-time",
    location: "Jakarta, Indonesia",
    responsibilities: [
      "Assigned to build Search Platform Dashboard from scratch.",
      "Fixing bugs on their Dynamic Filter Price Field that result in user can input/edit value and the selection cursor still in place not restarted from behind.",
      "Create a catalog feature that gives specification on the device when user search.",
      "Maintaining current Search and Find page.",
    ],
    current: false,
  },
  {
    title: "Frontend Engineer",
    period: "February 2021 – August 2022",
    company: "Topremit",
    employmentType: "Full-time",
    location: "Medan, Indonesia",
    responsibilities: [
      "Supervise code quality by doing thorough code review that result in stable, maintainable, and scalable application.",
      "Given responsibility to act as PIC of Web application.",
      "Developed reusable UI components that follows Topremit Design System to be used in whole web application in Topremit.",
      "Involving in the core application to research new technology that want to be implemented in the application.",
      "Involve in Mobile Development using React Native.",
      "Assigned to rebuild Topremit Internal Admin System.",
      "Assigned to build Topremit for Business from scratch",
      "Sharing knowledge across FE Engineer regarding best practices and new technology research.",
      "Teach in Topremit FE Internship program, that results in most of the interns are being promoted as full-time Frontend Engineer in Topremit.",
    ],
    current: false,
  },
];
